name: ci-test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install golang-migrate
        run: |
          set -e  # Stop the script if any command fails
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz -o migrate.tar.gz
          tar -xvzf migrate.tar.gz  # Extract the tar.gz file
          sudo mv migrate /usr/bin/migrate  # Move the binary to /usr/bin
          sudo chmod +x /usr/bin/migrate  # Ensure it is executable
          which migrate  # Check if migrate is in PATH

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -U root; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Run migrations
        run: make migrateup

      - name: Test
        run: make test
